<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TiendaSeeder extends Seeder
{
    public function run(): void
    {
        // ── 1. Proveedor ──────────────────────────────────────────────────────
        $proveedorId = DB::table('proveedores')->insertGetId([
            'nombre'      => 'Distribuidora Tech GT',
            'email'       => 'ventas@techgt.com',
            'telefono'    => '2222-3333',
            'direccion'   => 'Zona 4, Ciudad de Guatemala',
            'descripcion' => 'Distribuidor mayorista de tecnología',
            'estado'      => 'activo',
            'created_at'  => now(),
            'updated_at'  => now(),
        ]);

        // ── 2. Categorías ─────────────────────────────────────────────────────
        $cats = [];

        // Padres
        foreach ([
            'Computadoras'       => null,
            'Accesorios'         => null,
            'Audio'              => null,
            'Smartphones'        => null,
            'Redes'              => null,
        ] as $nombre => $parent) {
            $cats[$nombre] = DB::table('categorias')->insertGetId([
                'nombre'     => $nombre,
                'parent_id'  => $parent,
                'estado'     => 'activo',
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        // Hijos
        foreach ([
            'Laptops'             => 'Computadoras',
            'Escritorio'          => 'Computadoras',
            'Periféricos'         => 'Accesorios',
            'Almacenamiento'      => 'Accesorios',
            'Audífonos'           => 'Audio',
            'Bocinas'             => 'Audio',
            'Tablets'             => 'Smartphones',
            'Redes & Wi-Fi'       => 'Redes',
        ] as $nombre => $padre) {
            $cats[$nombre] = DB::table('categorias')->insertGetId([
                'nombre'     => $nombre,
                'parent_id'  => $cats[$padre],
                'estado'     => 'activo',
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        // ── 3. Productos ──────────────────────────────────────────────────────
        // [nombre, marca, color, precio_compra, precio_venta, precio_oferta|null,
        //  stock, garantia, descripcion, especificaciones, categorias[], imagen_unsplash]
        $productos = [
            [
                'sku'             => 'LAP-001',
                'nombre'          => 'Laptop HP 15 Core i5 12va Generación',
                'marca'           => 'HP',
                'color'           => 'Plata',
                'precio_compra'   => 3200.00,
                'precio_venta'    => 4500.00,
                'precio_oferta'   => 3999.00,
                'stock'           => 8,
                'stock_minimo'    => 2,
                'garantia'        => '1 año',
                'descripcion'     => 'Laptop ideal para trabajo y estudio. Procesador Intel Core i5 de 12va generación, pantalla Full HD de 15.6" y batería de larga duración.',
                'especificaciones'=> "Procesador: Intel Core i5-1235U\nRAM: 8 GB DDR4\nAlmacenamiento: 512 GB SSD NVMe\nPantalla: 15.6\" FHD IPS\nGráficos: Intel Iris Xe\nSO: Windows 11 Home\nBatería: 41 Wh",
                'categorias'      => ['Laptops', 'Computadoras'],
                'imagen'          => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853',
            ],
            [
                'sku'             => 'LAP-002',
                'nombre'          => 'Laptop Lenovo IdeaPad 3 Ryzen 5',
                'marca'           => 'Lenovo',
                'color'           => 'Gris',
                'precio_compra'   => 2800.00,
                'precio_venta'    => 3800.00,
                'precio_oferta'   => null,
                'stock'           => 5,
                'stock_minimo'    => 1,
                'garantia'        => '1 año',
                'descripcion'     => 'Laptop con procesador AMD Ryzen 5, perfecta para multitarea y entretenimiento. Diseño delgado y liviano.',
                'especificaciones'=> "Procesador: AMD Ryzen 5 5500U\nRAM: 8 GB DDR4\nAlmacenamiento: 256 GB SSD\nPantalla: 15.6\" FHD\nGráficos: AMD Radeon\nSO: Windows 11 Home",
                'categorias'      => ['Laptops', 'Computadoras'],
                'imagen'          => 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2',
            ],
            [
                'sku'             => 'LAP-003',
                'nombre'          => 'MacBook Air M2 13"',
                'marca'           => 'Apple',
                'color'           => 'Medianoche',
                'precio_compra'   => 7000.00,
                'precio_venta'    => 9500.00,
                'precio_oferta'   => null,
                'stock'           => 3,
                'stock_minimo'    => 1,
                'garantia'        => '1 año',
                'descripcion'     => 'La laptop más delgada y silenciosa de Apple. Chip M2 con hasta 18 horas de batería y pantalla Liquid Retina.',
                'especificaciones'=> "Chip: Apple M2\nRAM: 8 GB unificada\nAlmacenamiento: 256 GB SSD\nPantalla: 13.6\" Liquid Retina\nCámara: 1080p FaceTime HD\nSO: macOS Ventura",
                'categorias'      => ['Laptops', 'Computadoras'],
                'imagen'          => 'https://images.unsplash.com/photo-1611186871525-9b71b7e5c45a',
            ],
            [
                'sku'             => 'MON-001',
                'nombre'          => 'Monitor LG 24" Full HD IPS',
                'marca'           => 'LG',
                'color'           => 'Negro',
                'precio_compra'   => 900.00,
                'precio_venta'    => 1350.00,
                'precio_oferta'   => 1199.00,
                'stock'           => 12,
                'stock_minimo'    => 3,
                'garantia'        => '1 año',
                'descripcion'     => 'Monitor IPS de 24" con colores precisos y amplio ángulo de visión. Ideal para diseño, trabajo y gaming casual.',
                'especificaciones'=> "Tamaño: 24\"\nResolución: 1920×1080 Full HD\nPanel: IPS\nTasa de refresco: 75 Hz\nTiempo de respuesta: 5 ms\nConectividad: HDMI, VGA\nVESA: 100×100",
                'categorias'      => ['Escritorio', 'Periféricos'],
                'imagen'          => 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf',
            ],
            [
                'sku'             => 'TCLADO-001',
                'nombre'          => 'Teclado Mecánico Redragon K552 RGB',
                'marca'           => 'Redragon',
                'color'           => 'Negro',
                'precio_compra'   => 280.00,
                'precio_venta'    => 450.00,
                'precio_oferta'   => 399.00,
                'stock'           => 20,
                'stock_minimo'    => 5,
                'garantia'        => '6 meses',
                'descripcion'     => 'Teclado mecánico TKL con switches Blue táctiles y retroiluminación RGB. Construcción compacta sin teclado numérico.',
                'especificaciones'=> "Tipo: Mecánico TKL\nSwitches: Outemu Blue\nRetroiluminación: RGB\nConexión: USB\nN-Key Rollover: Sí\nMaterial: Aleación de aluminio",
                'categorias'      => ['Periféricos'],
                'imagen'          => 'https://images.unsplash.com/photo-1587829741301-dc798b83add3',
            ],
            [
                'sku'             => 'MOUSE-001',
                'nombre'          => 'Mouse Inalámbrico Logitech MX Master 3',
                'marca'           => 'Logitech',
                'color'           => 'Negro',
                'precio_compra'   => 500.00,
                'precio_venta'    => 750.00,
                'precio_oferta'   => null,
                'stock'           => 15,
                'stock_minimo'    => 3,
                'garantia'        => '2 años',
                'descripcion'     => 'El mouse más avanzado de Logitech. Sensor MagSpeed electromagnético, carga USB-C y compatible con múltiples dispositivos.',
                'especificaciones'=> "Conexión: Bluetooth / USB Nano\nSensor: 200–8000 DPI\nBatería: 70 días\nCarga: USB-C\nBotones: 7\nCompatibilidad: Windows, macOS, Linux",
                'categorias'      => ['Periféricos'],
                'imagen'          => 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46',
            ],
            [
                'sku'             => 'SSD-001',
                'nombre'          => 'SSD Kingston NV2 1TB NVMe M.2',
                'marca'           => 'Kingston',
                'color'           => 'N/A',
                'precio_compra'   => 350.00,
                'precio_venta'    => 520.00,
                'precio_oferta'   => null,
                'stock'           => 18,
                'stock_minimo'    => 4,
                'garantia'        => '3 años',
                'descripcion'     => 'SSD NVMe Gen 4 de 1 TB con velocidades de lectura de hasta 3500 MB/s. Perfecto para mejorar cualquier laptop o PC.',
                'especificaciones'=> "Capacidad: 1 TB\nInterfaz: PCIe 4.0 NVMe M.2\nLectura secuencial: 3500 MB/s\nEscritura secuencial: 2800 MB/s\nFactor de forma: 2280\nGarantía: 3 años",
                'categorias'      => ['Almacenamiento'],
                'imagen'          => 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b',
            ],
            [
                'sku'             => 'SSD-002',
                'nombre'          => 'Disco Duro Externo Seagate 2TB USB 3.0',
                'marca'           => 'Seagate',
                'color'           => 'Negro',
                'precio_compra'   => 380.00,
                'precio_venta'    => 580.00,
                'precio_oferta'   => 520.00,
                'stock'           => 10,
                'stock_minimo'    => 2,
                'garantia'        => '2 años',
                'descripcion'     => 'Disco duro externo portátil de 2 TB. Conexión USB 3.0 para transferencias rápidas. Compatible con Windows, Mac y consolas.',
                'especificaciones'=> "Capacidad: 2 TB\nConexión: USB 3.0\nVelocidad: 5 Gb/s\nCompatibilidad: Windows, macOS, Xbox, PS4/PS5\nDimensiones: 111.8×78.8×14.3 mm",
                'categorias'      => ['Almacenamiento'],
                'imagen'          => 'https://images.unsplash.com/photo-1531492746076-161ca9bcad58',
            ],
            [
                'sku'             => 'AUD-001',
                'nombre'          => 'Audífonos Sony WH-1000XM5 ANC',
                'marca'           => 'Sony',
                'color'           => 'Negro',
                'precio_compra'   => 1800.00,
                'precio_venta'    => 2800.00,
                'precio_oferta'   => 2500.00,
                'stock'           => 6,
                'stock_minimo'    => 1,
                'garantia'        => '1 año',
                'descripcion'     => 'Los mejores audífonos con cancelación de ruido del mercado. Hasta 30 horas de batería y calidad de audio premium.',
                'especificaciones'=> "Tipo: Over-ear inalámbrico\nCancelación de ruido: Sí (ANC)\nBatería: 30 horas\nCarga: USB-C (3 min = 3 horas)\nConexión: Bluetooth 5.2 / 3.5mm\nPeso: 250 g",
                'categorias'      => ['Audífonos', 'Audio'],
                'imagen'          => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e',
            ],
            [
                'sku'             => 'AUD-002',
                'nombre'          => 'Audífonos Gaming HyperX Cloud II',
                'marca'           => 'HyperX',
                'color'           => 'Rojo/Negro',
                'precio_compra'   => 500.00,
                'precio_venta'    => 750.00,
                'precio_oferta'   => null,
                'stock'           => 9,
                'stock_minimo'    => 2,
                'garantia'        => '2 años',
                'descripcion'     => 'Audífonos gaming con sonido 7.1 virtual, micrófono desmontable con cancelación de ruido y almohadillas de espuma viscoelástica.',
                'especificaciones'=> "Tipo: Over-ear\nSonido: 7.1 Virtual\nDriver: 53 mm\nMicrófono: Desmontable, cardioide\nConexión: USB / 3.5mm\nCompatibilidad: PC, PS4/5, Xbox, Switch",
                'categorias'      => ['Audífonos', 'Audio'],
                'imagen'          => 'https://images.unsplash.com/photo-1546435770-a3e426bf472b',
            ],
            [
                'sku'             => 'EARB-001',
                'nombre'          => 'Audífonos Inalámbricos JBL Tune 510BT',
                'marca'           => 'JBL',
                'color'           => 'Azul',
                'precio_compra'   => 220.00,
                'precio_venta'    => 380.00,
                'precio_oferta'   => 320.00,
                'stock'           => 14,
                'stock_minimo'    => 3,
                'garantia'        => '1 año',
                'descripcion'     => 'Audífonos on-ear con sonido Pure Bass JBL, 40 horas de batería y plegables para mayor portabilidad.',
                'especificaciones'=> "Tipo: On-ear plegable\nBatería: 40 horas\nCarga: USB-C (2 horas carga completa)\nConexión: Bluetooth 5.0\nDriver: 32 mm\nPeso: 160 g",
                'categorias'      => ['Audífonos', 'Audio'],
                'imagen'          => 'https://images.unsplash.com/photo-1558756520-22cfe5d382ca',
            ],
            [
                'sku'             => 'SPKR-001',
                'nombre'          => 'Bocina Bluetooth JBL Flip 6',
                'marca'           => 'JBL',
                'color'           => 'Negro',
                'precio_compra'   => 600.00,
                'precio_venta'    => 950.00,
                'precio_oferta'   => null,
                'stock'           => 7,
                'stock_minimo'    => 2,
                'garantia'        => '1 año',
                'descripcion'     => 'Bocina portátil con sonido potente, resistente al agua IP67. Hasta 12 horas de reproducción continua.',
                'especificaciones'=> "Potencia: 30 W\nResistencia: IP67 (agua y polvo)\nBatería: 12 horas\nCarga: USB-C\nConexión: Bluetooth 5.1\nPartyBoost: Sí",
                'categorias'      => ['Bocinas', 'Audio'],
                'imagen'          => 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1',
            ],
            [
                'sku'             => 'SMRT-001',
                'nombre'          => 'Samsung Galaxy A55 5G 128GB',
                'marca'           => 'Samsung',
                'color'           => 'Azul Marino',
                'precio_compra'   => 1800.00,
                'precio_venta'    => 2500.00,
                'precio_oferta'   => 2299.00,
                'stock'           => 10,
                'stock_minimo'    => 2,
                'garantia'        => '1 año',
                'descripcion'     => 'Smartphone con pantalla Super AMOLED de 6.6", cámara de 50 MP y batería de 5000 mAh. Compatible con 5G.',
                'especificaciones'=> "Pantalla: 6.6\" Super AMOLED 120 Hz\nProcesador: Exynos 1480\nRAM: 8 GB\nAlmacenamiento: 128 GB\nCámara: 50+12+5 MP\nBatería: 5000 mAh\nSO: Android 14",
                'categorias'      => ['Smartphones'],
                'imagen'          => 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf',
            ],
            [
                'sku'             => 'SMRT-002',
                'nombre'          => 'iPhone 15 128GB',
                'marca'           => 'Apple',
                'color'           => 'Rosa',
                'precio_compra'   => 5500.00,
                'precio_venta'    => 7200.00,
                'precio_oferta'   => null,
                'stock'           => 4,
                'stock_minimo'    => 1,
                'garantia'        => '1 año',
                'descripcion'     => 'iPhone con chip A16 Bionic, cámara dual de 48 MP y Dynamic Island. Puerto USB-C y carga rápida.',
                'especificaciones'=> "Pantalla: 6.1\" Super Retina XDR\nChip: A16 Bionic\nRAM: 6 GB\nAlmacenamiento: 128 GB\nCámara: 48+12 MP\nBatería: ~3877 mAh\nSO: iOS 17",
                'categorias'      => ['Smartphones'],
                'imagen'          => 'https://images.unsplash.com/photo-1695048133142-1a20484d2569',
            ],
            [
                'sku'             => 'TBLT-001',
                'nombre'          => 'iPad 10ma Generación 64GB Wi-Fi',
                'marca'           => 'Apple',
                'color'           => 'Plateado',
                'precio_compra'   => 2800.00,
                'precio_venta'    => 3800.00,
                'precio_oferta'   => null,
                'stock'           => 5,
                'stock_minimo'    => 1,
                'garantia'        => '1 año',
                'descripcion'     => 'iPad con pantalla Liquid Retina de 10.9", chip A14 Bionic y cámara frontal en modo horizontal. Ideal para estudio y entretenimiento.',
                'especificaciones'=> "Pantalla: 10.9\" Liquid Retina\nChip: A14 Bionic\nAlmacenamiento: 64 GB\nConectividad: Wi-Fi 6\nCámara trasera: 12 MP\nBatería: 28.65 Wh\nSO: iPadOS 17",
                'categorias'      => ['Tablets', 'Smartphones'],
                'imagen'          => 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0',
            ],
            [
                'sku'             => 'TBLT-002',
                'nombre'          => 'Tablet Samsung Galaxy Tab A9+ 64GB',
                'marca'           => 'Samsung',
                'color'           => 'Grafito',
                'precio_compra'   => 1400.00,
                'precio_venta'    => 2100.00,
                'precio_oferta'   => 1899.00,
                'stock'           => 8,
                'stock_minimo'    => 2,
                'garantia'        => '1 año',
                'descripcion'     => 'Tablet con pantalla LCD de 11", cuatro altavoces y soporte para S Pen. Perfecta para ver contenido y trabajar.',
                'especificaciones'=> "Pantalla: 11\" LCD 90 Hz\nProcesador: Snapdragon 695\nRAM: 4 GB\nAlmacenamiento: 64 GB + microSD\nCámara: 8+5 MP\nBatería: 7040 mAh\nSO: Android 13",
                'categorias'      => ['Tablets', 'Smartphones'],
                'imagen'          => 'https://images.unsplash.com/photo-1561154464-82e9adf32764',
            ],
            [
                'sku'             => 'WEBCAM-001',
                'nombre'          => 'Webcam Logitech C920 Full HD',
                'marca'           => 'Logitech',
                'color'           => 'Negro',
                'precio_compra'   => 420.00,
                'precio_venta'    => 650.00,
                'precio_oferta'   => 580.00,
                'stock'           => 11,
                'stock_minimo'    => 2,
                'garantia'        => '2 años',
                'descripcion'     => 'Webcam Full HD 1080p con enfoque automático y doble micrófono estéreo. Ideal para videollamadas y streaming.',
                'especificaciones'=> "Resolución: 1080p / 30fps\nEnfoque: Automático\nMicrófono: Doble estéreo\nAngulo de visión: 78°\nConexión: USB\nCompatibilidad: Windows, macOS, Chrome OS",
                'categorias'      => ['Periféricos'],
                'imagen'          => 'https://images.unsplash.com/photo-1587038838085-f9c0a9a63f5f',
            ],
            [
                'sku'             => 'ROUT-001',
                'nombre'          => 'Router TP-Link Archer AX73 Wi-Fi 6',
                'marca'           => 'TP-Link',
                'color'           => 'Negro',
                'precio_compra'   => 700.00,
                'precio_venta'    => 1100.00,
                'precio_oferta'   => null,
                'stock'           => 6,
                'stock_minimo'    => 1,
                'garantia'        => '2 años',
                'descripcion'     => 'Router Wi-Fi 6 AX5400 con antenas de alta ganancia y tecnología OFDMA. Ideal para hogares con múltiples dispositivos.',
                'especificaciones'=> "Estándar: Wi-Fi 6 (802.11ax)\nVelocidad: AX5400 (574+4804 Mbps)\nBanda: Doble (2.4 GHz + 5 GHz)\nAntenas: 6 externas\nPuertos: 1 WAN + 4 LAN Gigabit\nMU-MIMO: 4×4",
                'categorias'      => ['Redes & Wi-Fi', 'Redes'],
                'imagen'          => 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31',
            ],
            [
                'sku'             => 'HUB-001',
                'nombre'          => 'Hub USB-C 7 en 1 Anker',
                'marca'           => 'Anker',
                'color'           => 'Gris',
                'precio_compra'   => 180.00,
                'precio_venta'    => 320.00,
                'precio_oferta'   => null,
                'stock'           => 22,
                'stock_minimo'    => 5,
                'garantia'        => '18 meses',
                'descripcion'     => 'Hub 7 en 1 con USB-C Power Delivery 100W, HDMI 4K, 3 puertos USB-A, lector SD y microSD. Compacto y portátil.',
                'especificaciones'=> "Puertos: HDMI 4K@30fps, 3×USB-A 3.0, USB-C PD 100W, SD, microSD\nPD: Hasta 100 W\nMaterial: Aluminio\nLongitud cable: 25 cm\nCompatibilidad: MacBook, iPad Pro, Windows",
                'categorias'      => ['Periféricos', 'Accesorios'],
                'imagen'          => 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef',
            ],
            [
                'sku'             => 'PAD-001',
                'nombre'          => 'Mouse Pad XL Redragon P036 900×400mm',
                'marca'           => 'Redragon',
                'color'           => 'Negro',
                'precio_compra'   => 60.00,
                'precio_venta'    => 120.00,
                'precio_oferta'   => 99.00,
                'stock'           => 30,
                'stock_minimo'    => 8,
                'garantia'        => '6 meses',
                'descripcion'     => 'Mouse pad de tela extra grande que cubre toda tu área de trabajo. Base antideslizante y bordes cosidos para mayor durabilidad.',
                'especificaciones'=> "Dimensiones: 900×400×3 mm\nMaterial: Tela de microfibra\nBase: Goma antideslizante\nBordes: Cosidos\nCompatibilidad: Todo tipo de mouse",
                'categorias'      => ['Periféricos', 'Accesorios'],
                'imagen'          => 'https://images.unsplash.com/photo-1593640408182-31c228af44b9',
            ],
        ];

        foreach ($productos as $data) {
            $categorias = $data['categorias'];
            $imagen     = $data['imagen'];
            unset($data['categorias'], $data['imagen']);

            $productoId = DB::table('productos')->insertGetId(array_merge($data, [
                'proveedor_id' => $proveedorId,
                'estado'       => 'activo',
                'created_at'   => now(),
                'updated_at'   => now(),
            ]));

            // Imagen principal (usando Unsplash con parámetros de tamaño)
            DB::table('imagenes_producto')->insert([
                'producto_id'    => $productoId,
                'url'            => $imagen . '?w=800&q=80&auto=format&fit=crop',
                'url_thumb'      => $imagen . '?w=400&q=70&auto=format&fit=crop',
                'url_medium'     => $imagen . '?w=600&q=75&auto=format&fit=crop',
                'url_delete'     => null,
                'imgbb_id'       => null,
                'imgbb_data'     => null,
                'disk'           => 'external',
                'nombre_original'=> $data['sku'] . '-principal.jpg',
                'mime_type'      => 'image/jpeg',
                'tamaño'         => 150000,
                'es_principal'   => true,
                'orden'          => 0,
                'created_at'     => now(),
                'updated_at'     => now(),
            ]);

            // Asociar categorías
            foreach ($categorias as $catNombre) {
                if (isset($cats[$catNombre])) {
                    DB::table('categoria_producto')->insertOrIgnore([
                        'producto_id'  => $productoId,
                        'categoria_id' => $cats[$catNombre],
                        'created_at'   => now(),
                        'updated_at'   => now(),
                    ]);
                }
            }
        }
    }
}